### PR TITLE
feat: support custom transformers

### LINKED ISSUE #1558: Allow custom transformers
## Type of Issue

```
[ ] Bug Report
[x] Feature Request
```

## Description

There are a number of awesome TypeScript libraries which leverage the power of typescript transformers.

Unfortunately, it is not possible to use any of those with ng-packagr at the moment because ng-packagr doesn't let users add custom transformers to the typescript build.

One nice way to expose this feature would be to recognize the `plugins` option in `tsconfig.json` as is currently done by [ttypescript](https://github.com/cevek/ttypescript).

---

Some people are so desperate for this feature, they have gone to [insane length](https://medium.com/joolsoftware/custom-typescript-transformers-with-angular-cli-7f4150797e05) in order to inject custom transformers in the build pipeline of angular.
However, the above hack is based on webpack and so it cannot work with ng-packagr. A better alternative would be to provide official support for transformers.

### PR DESCRIPTION
**Pull request by hmil**
I'm submitting a...

```
[ ] Bug Fix
[x] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [x] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [x] Tests for the changes have been added

## Description

Add support for custom TypeScript transformers.

The interface is based on that of [ttypescript](https://github.com/cevek/ttypescript): Users can specify custom transformers in `tsconfig.json`.

### Killer use case

I need this feature in ng-packagr for the following use-case:

We develop our UI in independent modules for each business units. A shared platform library allows individual modules to interact with each other and with the application chrome. We would like to add type assertions at the entry points of the platform to prevent corrupted data from one module from propagating into the other modules (you don't want the virus to spread, am-I-right? 😅).
Without this kind of barrier, we see programming mistakes by one team blow up in the otherwise perfectly type-safe code of another team. Tracing back to the root cause is very time consuming.

I want to add [typescript-is](https://github.com/woutervh-/typescript-is) to offer platform developers an easy way to guard their API entry points against corrupted data, and prevent any kind of horizontal propagation of ill typed data.

### Other use cases

- [ts-optchain](https://github.com/rimeto/ts-optchain) on a project which is not on TS 3.7 yet and therefore can't use language-level optional chaining.
- See more examples of transformers on the homepage of [ttypescript](https://github.com/cevek/ttypescript). Note that not all of them are applicable with this patch as I mentioned above, and not all of them make sense in the context of an angular application.

#### Why ng-packagr?

A search for "typescript custom transformers" and "angular custom transformers" shows that there is some interest in the community for this feature.
The TypeScript team have expressed that they don't intend to make non-programmatic custom transformers part of the main compiler. So it makes sense to also not make it a part of the angular compiler.
People generally supply custom transformers through the build tool, usually webpack (some have reported using ngx-build-plus to inject custom transformers in the webpack config of the regular angular build tool. Though this is super hacky...).
Because ng-packagr doesn't use webpack users are left with no option.
This is why it makes sense to add this feature to ng-packagr and not at some other point in the stack.

#### Supported config options

The config settings suggested by ttypescript are nowhere near standard. I actually find some of these to be gimmicky at best, like the `import` key (of which I have never seen an equivalent anywhere) or the fact that it can load unprocessed typescript files with ts-node (effectively loading ts-node into the process of the typescript compiler... what could go wrong).

If a standard for packaged custom typescript transformers should emerge some day, then it's best to only support the bare minimum now and avoid all gadgets, because these gadgets might not make it into the standard and would break retro-compatibility.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

Closes #1558

### CODE REVIEW

**Comment by klemenoslaj** [comment]
It would be very nice to get the official support for the custom transformers. Right now the only way to do anything in this direction would be using `ng-cli-packagr-tasks` and relying on an unsupported APIs. This is of course a no-go for any serious project.

More: https://github.com/angular/angular-cli/issues/17963#issuecomment-646566775

This goes as far as blocking certain data layer decisions (issue above), which for an unopinionated project should not be the case (unsupported API after all is still blocking).

**Comment by ramarivera** [comment]
Hello, we've found ourselves trying to bundle a lot of nx libraries into a single bundled library thro ng packager. However we require some custom transformers for this, and this pr seems to allow exactly that. Is there any plan to merge it?

**Comment by hmil** [comment]
@ramarivera As far as I can tell this repo is not maintained.

**Comment by SchnWalter** [comment]
I'm not sure if you follow the commits, but this repository is properly maintained. The dependencies are updated when they need to be updated, security updates are added on a timely manner and support for newer Angular versions is added during alpha and beta phases and by the time we have a stable release, the library works perfectly, this is what it means for a library to be maintained.

Probably you think that this library is not maintained because you didn't get any feedback you your PR. Even though I'm not a maintainer of this library, I can think of at least a couple of reasons why this has happened. I also have 2 PRs that are not merged yet, but I'm not complaining because the PRs where I've only added tests have been merged very quickly, it's just a matter of priorities. I think that when the maintainers will have time for such PRs, they will look over them, until them, we have to wait.

Also, maintaining a library is lot of work, so when one ads new features, they also dedicate to making sure that the feature will work in the foreseeable future. This PR depends on `typescript-is` which depends on a lot of TypeScript internals and this simply means that for any significant change in the TypeScript internals, somebody will have to update the library, which, at the moment is managed by a single individual and it has about 2000 weekly installs, that code has all the chances in the world to become abandon-ware. So, even though I would like such a feature for the projects I work on, this exact implementation will get a big 👎, just because it is very fragile. If you can refactor the code to get rid of the new dependencies and not add complex code that depend on TS internals, then you'll definitely get a 👍 from me.

**Comment by hmil** [comment]
I understand the difficulty of maintaining a project like this one, and I understand that the proposed change has drawbacks.

However, after several months and at least one major angular release, both the issue describing the feature request and the PR demonstrating the concept have received no feedback at all. You'd expect that by this time, the issue would at least have been triaged, even if rejected.
And this is not an isolated case, many issues on this repo have been completely ignored. Neither turned down, neither accepted, merely lingering in the limbo of the would be.
It could be that the maintainers don't have bandwidth to accept outside feature requests, and that's fine. But if this is the case, then lock down the issues section. There are plenty of automation solutions available to help triage issues. If my issue had been immediately turned down by a bot, explaining that at the time feature requests cannot be accepted, then I would have understood and moved on.

So yes, I as far as I can tell the repo is not maintained.

---

Now for some real rant.

Angular ships ng-packagr as the default way to bundle libraries, an officially supported feature of the framework. How many were shoked to discover that the official build tool is in fact not officially supported by the core team?

The Angular project tried to play out of its league: a runtime, a compiler, a cli, ... what does it not do? You'd need an army of devs to maintain something this big. They lock us (users) in their half baked, poorly documented, totalitarian toolchain, in part maintained by third parties like the brave maintainer of ng-packagr. They favored the "out of the box" wow at the expense of own-ability and customizability.

I would have loved to get rolling with only the runtime of angular and a Webpack plugin, then I could have leveraged the most powerful and [well-funded](https://medium.com/open-collective/funding-open-source-how-webpack-reached-400k-year-dfb6d8384e19) build ecosystem in the nodejs ecosystem to customize my build at will.  
But no. Instead, Angular chose to go full walled garden mode and even [removed the last remaining hope](https://stackoverflow.com/questions/49892175/how-to-build-angular-2-app-without-cli#comment100604121_49892355) from their toolset. My only option now is to submit feature requests on an understaffed third party package.

Don't get me wrong, I have immense respect for the package maintainer, and I am aware of the [challenges of open source in the era of SaaS](https://feross.org/funding-experiment-recap/). I just wish that a package which ships as part of the mandatory stock configuration of Angular had official support from Angular and effective issue triaging.

**Comment by klemenoslaj** [comment]
@hmil even tho a harsh reply, I ended up agreeing with most of what you're saying.

Maintaining such a project is a lot of work, but the real issue is really with Angular CLI not being customizable in any way. Now some people might immediately counter that statement with: "but you can use custom builders". And sure, just not for libraries. So any serious project containing multiple libraries is pretty much blocked.

As I explained in [this comment](https://github.com/angular/angular-cli/issues/17963#issuecomment-647588218), this blocks some choices of technologies, but maintainers still call it "unopinionated".

> I would have loved to get rolling with only the runtime of angular and a Webpack plugin

That would honestly be good. Angular could still have the CLI for initial setup and schematics independently, without blocking the build.

**Comment by SchnWalter** [comment]
FYI, if you didn't see the `RFC: Ivy Library Distribution` (https://github.com/angular/angular/issues/38366) - you might wanna look into it, it's a long read, but a good one, there are some big changes in store for the Angular compiler; which will also affect ng-packagr, and I had a couple of questions that are somewhat related to this PR, here's the reply I got:

> https://github.com/angular/angular/issues/38366#issuecomment-676804371

**Comment by alan-agius4** [comment]
Hi all, sorry for the super late triaging of this one.

Firstly, thanks for putting this PR together. I don't think that custom TypeScript transformers will be supported and part of the API in the near future, the biggest thing is that they are not supported by the Angular compiler (IMHO for good reasons) See: https://github.com/angular/angular/issues/22434#issuecomment-594074902

As mentioned by Alex in the linked issue above, TypeScript transformers have a lot of gotchas which can easily break the library output.

**Pull request closed without merging**
