### PR TITLE
fix:  fix secondary entrypoints dependencies

### PR DESCRIPTION
**Pull request by jiayisheji**
I wanted to use secondary entrypoints packaging, but found that their packaging dependencies were sorted by folder, so that if there were dependencies there would be a packaging error.

```
[x] Bug Fix
[ ] Feature
[ ] Other (Refactoring, Added tests, Documentation, ...)
```

## Checklist

- [ ] Commit Messages follow the [Conventional Commits](https://conventionalcommits.org/) pattern
  - A feature commit message is prefixed "feat:"
  - A bugfix commit message is prefixed "fix:"
- [ ] Tests for the changes have been added

## Description

I have stated in this question:

[https://github.com/ng-packagr/ng-packagr/issues/1337](https://github.com/ng-packagr/ng-packagr/issues/1337)

I found manually setting dependencies not very friendly, and I looked through the code to set it to automatically get the list of dependencies and automatically handle the rest of the packaging

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by alan-agius4** [comment]
Hi @jiayisheji, thanks for this. Can you please provide a reproduction of the problem?

**Comment by hiepxanh** [comment]
@alan-agius4 the usecase is simple, you have two entry point: `@app/appointments` and `@app/patients`. 

ok that nice, I open `appointments.service.ts` file, then inject `{ Patient } from "@app/patients"` just keep error but. If I open `patients.service.ts` file, then inject `{ Appointment } from "@app/appointments"`. it work perfectly because packaging building process were "sorted by folder"

**Comment by alan-agius4** [comment]
Thanks for explanation will try to have a look in the coming days

**Comment by hiepxanh** [comment]
Thank you sir, have a nice day

**Comment by alan-agius4** [comment]
Hi, @hiepxanh, I tried to take a look and didn't manage to replicate it I see that the dependency graph is being populated correctly and also we have a test case were this same scenario is being tested https://github.com/ng-packagr/ng-packagr/tree/master/integration/samples/secondary


```cmd
------------------------------------------------------------------------------
Building entry point '@sample/secondary'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built @sample/secondary

------------------------------------------------------------------------------
Building entry point '@sample/secondary/shared'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @sample/secondary/shared

------------------------------------------------------------------------------
Building entry point '@sample/secondary/sub-module'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @sample/secondary/sub-module

------------------------------------------------------------------------------
Building entry point '@sample/secondary/feature-a'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @sample/secondary/feature-a

------------------------------------------------------------------------------
Building entry point '@sample/secondary/feature-b'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @sample/secondary/feature-b

------------------------------------------------------------------------------
Building entry point '@sample/secondary/feature-c'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Built @sample/secondary/feature-c

------------------------------------------------------------------------------
Built Angular Package!
 - from: /home/circleci/repo/integration/samples/secondary
 - to:   /home/circleci/repo/integration/samples/secondary/dist
------------------------------------------------------------------------------
Built.
Building sample ./integration/samples/typings/ng-package.json...
Building Angular Package

```

Can you please provide a reproduction and which version of ng-packagr you are using? Thanks.

**Comment by jiayisheji** [comment]
@alan-agius4 I found that the new version has been improved. I had this problem with the old version, but I was able to keep paying attention to it

**Comment by hiepxanh** [comment]
@alan-agius4 oh, thank you sir, after update to the new version, it seem working now. That really good, Thank you so much, I'm feel satisfiled now, Have a good day sir

**Comment by alan-agius4** [comment]
Awesome, have a good day you too.

Closing the PR as this seems to be solved. Thanks anyways for your contribution.

**Comment by hiepxanh** [comment]
image
image
I don't understand, apply on the newest project, and I have this error 
`patient.model.ts' is not under 'rootDir' 'E:\project\cc-ivy\projects\app-state\appointments'. 'rootDir' is expected to contain all source files.`
running ` ng build app-state --watch` and it build theses endpoint one by one, I have the same struture with your example project I don't undestand what did I wrong sir, If you don't mind, can you help me? @alan-agius4

**Comment by alan-agius4** [comment]
Line 2: seems to be the problem cause you are importing the file directly instead of using the library path

**Comment by hiepxanh** [comment]
I found my problem in this open issues 🤓 I will follow this issue
> Basically the owne, @dherges, want us to run ng-packagr for each library.
> If so, my question is how we build ONE package to include all library.
[This issues](https://github.com/ng-packagr/ng-packagr/issues/358#issuecomment-387799752)

**Comment by hiepxanh** [comment]
thank you sir

**Pull request closed without merging**
