### PR TITLE
fix: overhaul the stylesheet pipeline

### LINKED ISSUE #1873: Files loaded by the StylesheetProcessor are not added to the graph
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

If a style file is loaded by the [nodeSassTildeImporter](https://github.com/ng-packagr/ng-packagr/blob/master/src/lib/styles/stylesheet-processor-worker.ts#L56) it is not added to the build graph and if that file changes, a new build is not triggered.

#### How To Reproduce

Folder structure:
```
├───app
│       app.component.html
│       app.component.scss
│       app.component.ts
│       app.varibales.scss
│       index.ts
│
├───app-header
│       app-header.component.html
│       app-header.component.scss
│       app-header.component.ts
│       app-header.service.ts
│       index.ts
│
├───app-menu
│       app-menu.component.html
│       app-menu.component.scss
│       app-menu.component.ts
│       app-menu.service.ts
│       index.ts
```
`app.variables.scss`
```
$header-height: 60px;
$view-port-menu: 280px;
```

`app-header.component.scss`
```
@import '../app/app.varibales.scss';

.app-header {
    height: $header-height;
}
```

`app-menu.component.scss`
```
@import '../app/app.varibales.scss';

.app-menu {
    width: $view-port-menu;
}
```

If a change is made to the `app.variables.scss` file ( which is only used in import statements and not directly in `styleUrls` of a component  ), a new build is not triggered.

#### Expected Behaviour

If a change is made to a file imported in a style file, then a new build should be triggered.

#### Version Information

```
ng-packagr: 11.2.0
@angular/*: 11.2.0
typescript: 4.1.5
rxjs: 6.3.3
node: 14.15.4
npm/yarn: 1.22.5
```

### LINKED ISSUE #2654: bug: "Can't find stylesheet to import" when using Yarn PnP
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When migrating our library to use Yarn PnP, it's no longer resolving the `@angular/material` sass api at build time.  This resolved fine prior to the pnp shift.  `@angular/material` is declared as a peer dependency of the library (and installed as devDep for testing)

```bash
× Compiling with Angular sources in Ivy partial compilation mode.
Can't find stylesheet to import.
  ╷
6 │ @use '@angular/material' as mat;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵

```

#### How To Reproduce

In a library project within a repo using yarn pnp, try using the root sass api from `@angular/material` within a component's stylesheet.
```scss
@use '@angular/material' as mat;
```

When building, it should fail to resolve.

#### Expected Behaviour

Should build successfully

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 16.1.0
@angular/*: 16.1.2
typescript: 5.1.6
rxjs: 7.8.1
node: 16.19.0
yarn: 3.6.0
```

### LINKED ISSUE #2660: Component styles not rebuild when changing imported scss files after first build
## Type of Issue

```
[x] Bug Report
[ ] Feature Request
```

## Description

When trying to use scss `@import` features in a component scss file the component doesn't get recompiled/rebuild when editing the imported file while the build is running with `--watch`. Only when saving/changing again the component scss file the changes are taken up. Also on first build the import works as intended. The same happens when using the `@use` rule.

In my case I had one scss file where I wanted to have some shared styles and variables which I wanted to use in multiple components. Now each time I change something in the shared styles scss file I would need to go to **each** component and update there the component styles file. Exposing them globally is not really an option for me as I wanted to still have those css rules scoped on the component.

#### How To Reproduce

[In this Stackblitz](https://stackblitz.com/edit/stackblitz-starters-vul56f?file=projects%2Fmy-library%2Fsrc%2Flib%2Fmy-library.component.scss&view=editor) the behavior can be reproduced. Just let first the initial build finish, then go to the shared file called `_shared-styles.scss` and change for example a color. In the terminal one can see that no rebuild gets triggered by that already. In the output file `dist/my-library/esm2022/lib/my-library.component.mjs` the changes are also missing. Then try to make a change in the scss file which is directly included by the component via `styleUrls` and save it, only now the components gets rebuild with the changes of the shared scss file. This can also be seen in the above mentioned output file.

#### Expected Behaviour

The components styles should update as well if imported files gets changed and not only on first build or when changing the scss file referenced by the component.

#### Version Information

```
ng-packagr: 16.1.0
@angular/*: 16.1.7
typescript: 5.1.6
rxjs: 7.8.1
node: 16.20.0 (locally I had v18 with the same behavior)
npm: 9.4.2
```

### LINKED ISSUE #2918: Embebed Assets on 18.2.1
## Type of Issue

```
[ x] Bug Report
[ ] Feature Request
```

## Description

I have a library where we are exporting TTF (fonts) and SVG files, but it is not finding the relative path of these... so it is throwing the following errors:

image
image
image

#### How To Reproduce

1.- clone repo: https://github.com/gothaussencl/ng-packagr-error
2.- run command npm install
3.- run command ng build

#### Version Information

```
$ node_modules/.bin/ng-packagr --version
ng-packagr: 18.2.1
@angular/*: 18.2.4
typescript: 5.4.5
node: 22.8.0
npm/yarn: 10.8.2
```

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit updates the component stylesheet pipeline to align with the application builder. It introduces several improvements, including support for PNP, better handling of CSS resources, and enhanced management of transitive SCSS resources.

Closes #1873, closes #2918, closes #2660 and closes #2654

### CODE REVIEW

**Comment by Alanoll** [comment]
Is there any chance of this being release in the v18 branch?

**Comment by GusLAN** [comment]
@alan-agius4, Do you have an estimated date for a new release that includes the fix for the commit? Looking forward to it!

**Comment by alan-agius4** [comment]
This is part of v19, which is already available in the prerelease version.

**Comment by Alanoll** [comment]
> This is part of v19, which is already available in the prerelease version.

Any chance of a backport to v18, so it'll work with Angular v18? 
I saw the v19 prerelease is also targeting Angular v19 as a peer dep, so npm would refuse to install it for Angular v18 projects.

**Pull request merged**
