### PR TITLE
fix: error out gracefully when `package.json` is not found

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes: #1255

### CODE REVIEW

**Comment by SaranVairam** [comment]
@alan-agius4  , what is the fix i need to give , for making an successful package

**Comment by alan-agius4** [comment]
You most likely missing a `package.json` from a secondary entrypoint

**Comment by SaranVairam** [comment]
@alan-agius4 ..  didnt get you , but any way ,  i will try ..Thanks

**Comment by alan-agius4** [comment]
You most likely, have a missing `package.json` from a secondary entrypoint you are trying to import. This fix, will print out the path of the missing `package.json`

**Comment by SaranVairam** [comment]
But the second entry point is same is defined in the entry as well console print out file

**Pull request merged**
